name: Maven

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['1.8', '11', '17', '18']
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Maven Verify
        run: mvn verify

  deploy:
    name: Deploy Artifact
    needs: build
    if: ${{ needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          #distribution: 'temurin'
          java-version: '1.8'
          cache: 'maven'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven Deploy
        run: mvn deploy -DskipTests=true
        env:
          MAVEN_USERNAME: 'SingingBush'
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN  }}
