name: Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Test with Java ${{ matrix.jdk }}
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['8', '11', '17', '21', '22']
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: maven

      - name: Maven Verify
        run: mvn verify

# todo: setup aggregated Jacoco
#      # Only doing on one job
#      - name: Add coverage to PR
#        id: jacoco-report
#        if: ${{ matrix.jdk == '17' }}
#        uses: madrapps/jacoco-report@1.7.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#          min-coverage-overall: 80

  analysis:
    name: Static Analysis
    needs: build
    continue-on-error: false
    if: ${{ needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # for actions/checkout to fetch code
      pull-requests: write # for attached results to PR
      checks: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0  # a full history is required for pull request analysis

    ## latest Sonar requires Java 17 or higher
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Setup Cache for SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    ## todo: use same artifacts from the build job
    ## Automatic Analysis is turned off on sonarcloud.io
    - name: Maven JaCoCo report & Sonar
      run: mvn -B install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=jour
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy Artifact
    needs: build
    if: ${{ needs.build.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven Deploy
        run: mvn deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ github.repository_owner }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN  }}
